### ISSUE TITLE
Provide examples in documentation

### ISSUE THREAD

**Issue by leanne1** [Financial-Times/o-viewport#13]
Across Origami, new users would benefit from concrete syntax examples in addition to code explanation. It is quicker for [new] users to look at some code samples than to try to formulate [guess] at code syntax from reading an explanation.

**Comment by notlee** [comment]
Hey, thanks for the suggestion. I've added a bunch of new examples, 1,668 days later! It will be released as part of a larger piece of work.

issue: https://github.com/Financial-Times/o-viewport/issues/58
pr: https://github.com/Financial-Times/o-viewport/pull/59
