### ISSUE TITLE
Don't polyfill screen.orientation

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-viewport#21]
Wait for https://github.com/Financial-Times/polyfill-service/pull/403 to land in polyfill service then  add screen.orientation as optional dep and remove https://github.com/Financial-Times/o-viewport/blob/master/main.js#L28 - 30

**Comment by onishiweb** [comment]
That's merged into the Polyfill service now, is it worth doing this now?

**Comment by AlbertoElias** [comment]
Are we still polyfilling it? I thought we had removed it already

**Comment by wheresrhys** [comment]
Yep https://github.com/Financial-Times/o-viewport/blob/master/src/utils.js#L51

I know it's just normalising the name, but technically should just be relying on polyfill service

**Comment by AlbertoElias** [comment]
Then it should be removed!

**Comment by notlee** [comment]
This is done, to be released as part of the breaking cascade. Closing to keep track of progress.

See:
issue: https://github.com/Financial-Times/o-viewport/issues/58
pr: https://github.com/Financial-Times/o-viewport/pull/59
