### ISSUE TITLE
getOrientation: what about watches and other square or round screens?

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/o-viewport#22]
e.g. What does a Moto 360 report when browsing a site? Is it correct for it to report landscape or portrait?

**Comment by AlbertoElias** [comment]
if you're using a web browser on a watch, you're doing something wrong. I really don't think we should consider it, at least not for a while

**Comment by kaelig** [comment]
> if you're using a web browser on a **phone**, you're doing something wrong

– Anyone, in 2006

**Comment by AlbertoElias** [comment]
Exactly, in 2006, making mobile sites wasn't a priority, probably not until 2008-2009. The watches can't handle native apps fluidly yet, it will take a while until web browsers run more or less alright on watches, and then people actually create an ecosystem there. And then I'm also of the opinion that smartwatches are just a temporary thing :P

**Comment by kaelig** [comment]
Having read the Guardian and BBC News on a watch recently, I think it is quite usable. But I guess the business value to know about these types of screen might be very limited. Closing.

**Comment by AlbertoElias** [comment]
Do you mean the actual website or the apps?

**Comment by triblondon** [comment]
I agree with Alberto.  It might be a thing, but right now it's nothing more than an interesting toy.  It could be a labs project, but shouldn't be on Origami's radar.

**Comment by kaelig** [comment]
> Do you mean the actual website or the apps?

The websites

**Comment by AlbertoElias** [comment]
Was it an Apple Watch? I know my watch can't even load a browser, but it's one of the worse out there

**Comment by kaelig** [comment]
It was a Moto 360. http://www.mobypicture.com/user/kaelig/view/17755517

**Comment by AlbertoElias** [comment]
At least it loads! It's still very far from usable keeping in mind it's a desktop site

**Comment by kaelig** [comment]
It's a mobile site actually! Responsive from 240 to ~1300 px if my memory serves me well. A bit slow to scroll but it loads and is readable and navigation works.

**Comment by AlbertoElias** [comment]
I much prefer the push notifications example they did at IO with the guardian where you received a notification on your watch about new content on the site via web push notifications.
